### ISSUE TITLE
Changing Report Look

### ISSUE THREAD

**Issue by themetalleg** [windingwind/zotero-plugin-template#29]
Hi, is there at the moment a way to change the look of the reports? To include costum fields for example or show images? I was not able to find anything in the documentation.

**Comment by MuiseDestiny** [comment]
can you give me some screenshots?

**Comment by windingwind** [comment]
Sorry for the delayed reply.

I am not sure what you mean by the `report`. Could you please give some screenshots or detailed descriptions?

**Comment by themetalleg** [comment]
![screenshot](https://user-images.githubusercontent.com/77667407/229362326-045f88b6-0d2d-4069-99d5-a87c2e3bd483.jpg)

No problem. Here is the screenshot. I mean the windows that opens, when you click "Generate Report from Items...".

**Comment by windingwind** [comment]
I am not sure why or how you want to change this window. Seem like you have to use a window open listener to trigger some style/script injection when this generating report window is opened.

An example from the toolkit: https://github.com/windingwind/zotero-plugin-toolkit/blob/43141190c7b85091fe5058bf253d1e97b13bec6e/src/managers/preferencePane.ts#L203-L280

However, I would suggest not modifying existing windows or modules of Zotero, unless you fully understand what you are doing. Adding new features is safe in most cases, while changing inner modules may cause unexpected errors or data loss unless you are sure you handled everything very well.

If you only want to make the report UI more user-friendly or beautiful, it's OK to inject some CSS; otherwise, I would recommend you add a new option for users to open a new window provided by your plugin/generate the report you want.

**Comment by themetalleg** [comment]
Yeah ok, that makes sense. Thank you. Will go this way.
