### ISSUE TITLE
Question on Zotero Version Requirement

### ISSUE THREAD

**Issue by lifan0127** [windingwind/zotero-plugin-template#36]
Thanks for creating this template which I found immensely useful.

Some of my users have experienced version compatibility issue, such as: https://github.com/lifan0127/ai-research-assistant/issues/16

Do you have any insight/guidance?

**Comment by windingwind** [comment]
Not sure which client version your users are using, I might need more information to help.

Updating configurations have a known bug, but I haven’t had time to fix it. I am traveling these days. You could refer to the pdf-translate plugin for the correct update.rdf and update.json

**Comment by huachuman** [comment]
I thought I read recently that zotero moved away from manifest.json. Is it possible this is happening because people were using an old version of this template?

**Comment by windingwind** [comment]
Sorry for the late reply. You can change the minimal version requirements from 6.999 to 5.999. This might be a problem with the template, but it's strange that I haven't heard of any related reports from users of PDF Translate or PDF Preview plugin.

I am travelling these days and do not have PC. I would be grateful if you can help me fix this with a PR. Thanks!

**Comment by windingwind** [comment]
I looked into the make-it-red repo, which is the official example for Zotero plugins, and they use the same manifest.json as we do. Generally speaking, the manifest.json only works on Zotero7 and the chrome.manifest works on Zotero6.

So this is not a bug, but a intentional design. As mentioned above, the min version requirements in the manifest.json will not cause any incompatibility issues.

**Comment by lifan0127** [comment]
Thanks for checking against the official make-it-red repo. I guess no change is needed now.

**Comment by github-young** [comment]
> I looked into the make-it-red repo, which is the official example for Zotero plugins, and they use the same manifest.json as we do. Generally speaking, the manifest.json only works on Zotero7 and the chrome.manifest works on Zotero6.
> 
> So this is not a bug, but a intentional design. As mentioned above, the min version requirements in the manifest.json will not cause any incompatibility issues.

Dear @windingwind, thank you for developing such a great template.

I am a beginner in the Zotero plugin and I am developing a naive plugin to add one new column to display the last author of all the items. The function is quite easy and I have achieved it on the `` main `` branch shown in the [`` examples.ts ``](https://github.com/github-young/zotero-last-author/blob/5f56e729d8e523315d540613660ef4cd41c242ce/src/modules/examples.ts#L35C1-L38C31):

```js
        var authors = item.getCreators();
        var lastAuthor = authors[authors.length - 1];
        var lastAuthorName = lastAuthor.lastName + ", " + lastAuthor.firstName;
        return lastAuthorName;
```

But when I run `` npm run build `` to get the compiled `` xpi `` package file, I found it can only be installed on Zotero 7 (the beta version I used to develop) instead of Zotero 6 (the version I am currently using) with the same problem as @huachuman stated in this issue.

I read through your documentation hosted on Yuque and this issue, but I don't quite understand how this issue was solved. Could you please let me know how I can build a `` xpi `` package for Zotero 6?

The version I want to install this plugin on is: Zotero 6.0.27

**Comment by northword** [comment]
@github-young 你的问题与上述关联不大。
当前主分支仅支持 zotero 7，如需构建支持 zotero 6 的插件，请使用 zotero7-bootstrap 分支。
鉴于当前 zotero7 已经逐渐完善，我个人建议直接基于 7 开发。
当前6与7的不兼容点主要在于本地化系统，你可同时放入dtd和flt以同时兼容6和7。
此外需要修改manifest.json中限制zotero版本的值，可以参考zotero插件开发官方文档关于向7迁移的部分。

不要参考语雀文档，语雀文档针对6，已经过时。如果你基于zotero6-bootstrap分支构建，可以参考。

关于同时支持6和7，可以参考better-bibtex插件。

**Comment by github-young** [comment]
@northword Thank you very much!

**Comment by windingwind** [comment]
@github-young 
Building a plugin that runs on both Zotero 6 and Zotero 7 can be painful and crazy for beginners, especially since Zotero 6 will soon reach the end of its support.

**Comment by huachuman** [comment]
I am still having issues installing plugins based on this template because of "incompatible" zotero versions. I am here to help give info on the issue because it is driving me totally insane that I have to go mess around in the chrome.manifest and manifest.json files to get my zotero to read these plugins.

I am and always have been on Zotero 6, in this case Zotero 6.0.30. The plugin that is causing issues for me in particular is https://github.com/lifan0127/ai-research-assistant

**Comment by windingwind** [comment]
@huachuman 
Please contact the author of the plugin. Sorry but I won't be able to help you with that.

**Comment by huachuman** [comment]
This is not a problem with the author of the plugin. I have had this issue with vritually every plugin that was created using this repo because the problem has to do with the template, not the individual plugins. The template is creating an issue with plugins appearing incompatible with zotero.

I have already asked the author about this, and they referred to this template being the issue. As a matter of fact, the author of that plugin is actually the author of this very thread inquiring here in response to my question.

**Comment by northword** [comment]
The manifest file of the template is consistent with the official plug-in example.

**Comment by huachuman** [comment]
I am not sure what you mean exactly by "give your all detailed manifest.json, install.rdf" so I will just copy paste the manifest.json and install.rdf from a non-working plugin, in this case the Aria plugin, followed by the modified manifest.json and install.rdf that work for me:

### Not working
original install.rdf: 
```
<?xml version="1.0"?>
<RDF:RDF
    xmlns:em="http://www.mozilla.org/2004/em-rdf#"
    xmlns:NC="http://home.netscape.com/NC-rdf#"
    xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <RDF:Description
        RDF:about="urn:mozilla:install-manifest"
        em:id="aria@apex974.com"
        em:name="Aria"
        em:version="0.5.5"
        em:type="2"
        em:creator="Fan Li"
        em:description="AI Research Assistant Powered by Large Language Models"
        em:homepageURL="https://github.com/lifan0127/ai-research-assistant#readme"
        em:iconURL="chrome://aria/content/icons/favicon.png"
        em:optionsURL="chrome://aria/content/preferences.xul"
        em:updateURL="https://raw.githubusercontent.com/lifan0127/ai-research-assistant/bootstrap/update.json"
        em:multiprocessCompatible="true"
        em:bootstrap="true">
        <em:targetApplication>
            <Description>
                <em:id>zotero@chnm.gmu.edu</em:id>
                <em:minVersion>5.0</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
        <em:targetApplication>
            <Description>
                <em:id>juris-m@juris-m.github.io</em:id>
                <em:minVersion>5.0</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
  </RDF:Description>
</RDF:RDF>
```
original manifest.json:
```
{
  "manifest_version": 2,
  "name": "Aria",
  "version": "0.5.5",
  "description": "AI Research Assistant Powered by Large Language Models",
  "author": "Fan Li",
  "icons": {
    "48": "chrome/content/icons/favicon@0.5x.png",
    "96": "chrome/content/icons/favicon.png"
  },
  "applications": {
    "zotero": {
      "id": "aria@apex974.com",
      "update_url": "https://raw.githubusercontent.com/lifan0127/ai-research-assistant/bootstrap/update.json",
      "strict_min_version": "6.999",
      "strict_max_version": "6.999"
    }
  }
}
```

### Working

modified install.rdf:
```
<?xml version="1.0"?>
<RDF:RDF
    xmlns:em="http://www.mozilla.org/2004/em-rdf#"
    xmlns:NC="http://home.netscape.com/NC-rdf#"
    xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <RDF:Description
        RDF:about="urn:mozilla:install-manifest"
        em:id="aria@apex974.com"
        em:name="Aria"
        em:version="0.5.5"
        em:type="2"
        em:creator="Fan Li"
        em:description="AI Research Assistant Powered by Large Language Models"
        em:homepageURL="https://github.com/lifan0127/ai-research-assistant#readme"
        em:iconURL="chrome://aria/content/icons/favicon.png"
        em:optionsURL="chrome://aria/content/preferences.xul"
        em:updateURL="https://raw.githubusercontent.com/lifan0127/ai-research-assistant/bootstrap/update.json"
        em:multiprocessCompatible="true"
        em:bootstrap="true">
        <em:targetApplication>
            <Description>
                <em:id>zotero@chnm.gmu.edu</em:id>
                <em:minVersion>5.0</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
        <em:targetApplication>
            <Description>
                <em:id>juris-m@juris-m.github.io</em:id>
                <em:minVersion>*</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
  </RDF:Description>
</RDF:RDF>
```

modified manifest.json
```
{
  "manifest_version": 2,
  "name": "Aria",
  "version": "0.5.5",
  "description": "AI Research Assistant Powered by Large Language Models",
  "author": "Fan Li",
  "icons": {
    "48": "chrome/content/icons/favicon@0.5x.png",
    "96": "chrome/content/icons/favicon.png"
  },
  "applications": {
    "zotero": {
      "id": "aria@apex974.com",
      "update_url": "https://raw.githubusercontent.com/lifan0127/ai-research-assistant/bootstrap/update.json",
      "strict_min_version": "*",
      "strict_max_version": "*"
    }
  }
}
```
To be clear I am skeptical that the install.rdf changes are relevant. I'm quite certain it has to do with the manifest.json.

Again, keep in mind I AM running Zotero 6.0.30. NOT any kind of beta build nor Z7. This has been a problem for a very long time now, probably longer than a year or two.

**Comment by windingwind** [comment]
I have to point out that what you are doing right now is very rude and offensive. If your steak is overcooked, complain to the chef, not the farmer.

Before accusing someone that voluntarily contributes to the community, make sure you really read the readme. I explained clearly that the current main branch only supports Z7 and which branch you’re going to use for other versions of Z.

If we don’t want to support some version, then we don’t. Welcome to open source.

**Comment by huachuman** [comment]
Wow. You are incapable of reading.

**Comment by northword** [comment]
不能理解，模板的主分支是基于 Zotero 7 的，这一点在自述文件里写的很清楚。

如果你需要兼容 Zotero 6，你需要参考其他分支以修改 manifest.json 文件 和 install.rdf 文件。

如果你觉得复杂，应参考官方插件示例 make-it-red。模板与官方示例一致，是没有错误的。

如此多的插件基于本模板构建且正常兼容 6 或 7，在反馈前请认真阅读文档并多找找自己的问题，而不是指责别人，学会提问，学会学习。

**Comment by huachuman** [comment]
The plugins I am trying to install are advertised as compatible with Z6. I have no idea what the two of you are talking about, like I didn't read the documentation? 

All I am saying is these plugins use this template and say they are compatible with Z6. Yet when installing them, they throw a message that they are incompatible.

**Comment by northword** [comment]
>  If your steak is overcooked, complain to the chef, not the farmer.

如果你使用的插件有兼容性问题，向插件开发者反馈。

---

此外，这是一个面向开发者的模板仓库，在本仓库内的讨论当然会从开发者构建插件的角度说明本模板并未错误。

此外，模板已经停止了对 Zotero 6 的维护，在此之前，插件可以正常工作。

Zotero 6.0.27-beta.3+3e12f3f20 and Addon 0.5.5: 

![image](https://github.com/windingwind/zotero-plugin-template/assets/44738481/9bf44db0-508c-4479-8be1-910248c41b2d)

---

I think we can lock this issue.

**Comment by windingwind** [comment]
> The plugins I am trying to install are advertised as compatible with Z6

SO WHAT? DID I EVER WRITE A SINGLE WORD OF THAT SENTENCE?

> like I didn't read the documentation?

Definitely, you didn't:

https://github.com/windingwind/zotero-plugin-template#features

> All I am saying is these plugins use this template and say they are compatible with Z6. Yet when installing them, they throw a message that they are incompatible.

So if someone claims to support a specific version of Z but you think they actually don't - complain to them.

> It sounds like you think I'm a plugin developer or something, trying to make a plugin myself that is compatible with Z6 using the Z7 template. This is not the case, and indicates you are not at all reading what I am saying.

Nope. I now realize that you are just someone trying to argue for nonsense and spamming everyone in this repo.

Again, in case someone who didn't follow the discussion here:

1. the plugin template works well with the versions it is designed for. if you think there's a problem, show me evidence and/or create a PR
2. no one here claims that any plugin created with this template should be compatible with Z6 or Z7 or any specific version
3. if a plugin fails to run on a version of Z that it claims to support, none of my business.

**Comment by huachuman** [comment]
I believe the isses we are facing are mostly your lack of grasp of the english language.

I'm going to leave this place because we are not getting anywhere. Developers who I complained to about problems with compatibility point me to this repo. So do not tell me to complain to them because they are using this template.

You say if your steak is burnt then don't blame the farmer blame the cook. But your analogy makes no sense. You are the recipe maker, not the farmer. So when the cook burns the steak, it's because he followed the wrong recipe (your recipe).

Have you not read the many other comments online facing the same problem?

You are a clueless developer.

**Comment by windingwind** [comment]
> So far nobody has been able to explain to me why the plugin ONLY works after modifying the manifest.json despite your claim that Z6 doesn't read manifest.json? It looks like, "generally speaking" (your words, not mine) you are wrong. But you don't know how to admit it.

https://www.zotero.org/support/dev/zotero_7_for_developers#installrdf_manifestjson

Zotero 6 does not read the `manifest.json`. If you think it does, report to the zotero forums, not me.

Again,

1. The `zotero6-bootstrap` branch uses exactly the same config files as the official sample https://github.com/zotero/make-it-red/tree/main/src-1.2, so I am pretty sure there is nothing wrong. If you are talking about plugins created based on that branch, please, ask the repo owner for help. Btw this branch is staled and no longer maintained.
2. The `main` branch does not support Z6, so don't expect any plugins created based on that branch can be fully compatible to Z6 by just changing the config files. We do this for reasons.

By any means, I don't see it's reasonable to ask me to deal with your special case (though I doubt that) of another plugin.

**Comment by huachuman** [comment]
"Zotero 6 does not read the manifest.json."

If you were capable of reading you would see based on this experiment that zotero 6 clearly reads manifest.json.

Anyway, you are clearly of zero use in any form of conversation. Goodbye.
