### ISSUE TITLE
RightClickMenuItem vs RightClickMenuPopup

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#80]
For some reason, the right click popup menu only appears if the right click menu item is also registered. Why is that? How would you only add a right click popup menu without a right click menu item?

Also, for some reason the right click popup menu disappears if I change 

```ts
document.querySelector(
        "#zotero-itemmenu-addontemplate-test",
      ) as XUL.MenuItem,
```
to
```ts
document.querySelector(
        "#zotero-itemmenu-whatever",
      ) as XUL.MenuItem,
```

What am I missing here?

**Comment by windingwind** [comment]
> the right click popup menu only appears if the right click menu item is also registered

I am not sure I understand your question, but if you are talking about the `menupopup` element inside another `menupopup`, the element tree must be `menupopup -> menu -> menupopup -> menuitem` It always starts with a top-level `menupopup` and ends with a `menuitem`. If you have an `menupopup` without any child menu item, then it should just be a `menuitem`.

This line is for the third argument of `ztoolkit.Menu.register`, which is `anchorElem` and for locate the position to insert the new menu item. If the selector does not return a valid element as anchor, then it simply won't work.

In modern IDE, press cmd/ctrl and hover the function name, you'll see documents for how to use the API of plugin toolkit.

**Comment by denismaier** [comment]
Sorry, I wasn't particularly clear.
Comment out this line: https://github.com/windingwind/zotero-plugin-template/blob/12e7cb9641d9f19c8b2bf5a6e662b5f563ae7b9a/src/hooks.ts#L53C25-L53C25

Although `UIExampleFactory.registerRightClickMenuPopup()` is still registered it will not appear anymore in the context menu.

**Comment by windingwind** [comment]
Yes. 

https://github.com/windingwind/zotero-plugin-template/blob/12e7cb9641d9f19c8b2bf5a6e662b5f563ae7b9a/src/modules/examples.ts#L203-L209

Here we register a menu item with id `zotero-itemmenu-addontemplate-test` in `registerRightClickMenuItem`;

And in `registerRightClickMenuPopup` we use this id to find the anchor element and insert a menu popup before that anchor element, which is the menu item we just added before:

https://github.com/windingwind/zotero-plugin-template/blob/12e7cb9641d9f19c8b2bf5a6e662b5f563ae7b9a/src/modules/examples.ts#L228-L230

Since the `registerRightClickMenuItem` is comment out and the anchor element does not exist, the registration of menu popup fails.

**Comment by denismaier** [comment]
Ok, got it. I've just removed the `before` property. Works as expected now. Thanks again for your help.
